# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 15:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_date', models.DateField(default=datetime.datetime(2016, 10, 28, 15, 26, 17, 456000, tzinfo=utc))),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('role', models.IntegerField(default=0, max_length=1)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
