# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161028_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('address', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('seats_number', models.IntegerField(default=0)),
                ('auto_accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
