# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 15:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161029_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfirmationHash',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=16)),
                ('hash', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userconfirmationhash',
            unique_together=set([('type', 'hash')]),
        ),
    ]
