# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161030_1652'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserConfirmationHash',
            new_name='User_ConfirmationHash',
        ),
    ]
