# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_reservation_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability_Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField()),
                ('hour_from', models.IntegerField(default=0)),
                ('hour_to', models.IntegerField(default=24)),
                ('since', models.DateField(null=True)),
                ('until', models.DateField(null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Room')),
            ],
        ),
    ]
