# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 11:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_reservation_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability_room',
            name='hour_from',
            field=models.CharField(default='00:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='availability_room',
            name='hour_to',
            field=models.CharField(default='23:59', max_length=5),
        ),
        migrations.AlterField(
            model_name='availability_room',
            name='since',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='availability_room',
            name='until',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
