# -*- coding: utf-8 -*-
"""
Django settings for srs project.

Generated by 'django-admin startproject' using Django 1.10.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'i-p2sa857-20cm1by3!dn#42%-cejxq-kz_8hkuag6e=o@1-e4'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = False

ALLOWED_HOSTS = [
    "*"
]

# Application definition

INSTALLED_APPS = [
    'app',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'srs.urls'

TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            TEMPLATE_DIR
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES_HEROKU = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql', # django.db.backends.postgresql_psycopg2
        'NAME': 'dd422lckkhknme',
        'USER': 'mnjggxginbqxoc',
        'PASSWORD': 'js5SdAjPDr4w28UFMTKgV7xeOw',
        'HOST': 'ec2-54-75-232-46.eu-west-1.compute.amazonaws.com',
        'PORT': '5432',
    }
}

DATABASES_LOCALHOST = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql', # django.db.backends.postgresql_psycopg2
        'NAME': 'srs',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

DATABASES = DATABASES_LOCALHOST

# Auth

AUTH_USER_MODEL = 'app.User'

LOGIN_URL = '/sign_in'

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'pl-PL'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]


# Site

SITE_TITLE = 'System rezerwacji sal'


# Captcha

CAPTCHA_LENGTH = 6


# Email sender configuration SMTP

EMAIL_SMTP = {
    'HOST': 'smtp.gmail.com',
    'PORT': 587,
    'FROM_NAME': 'Automat | System rezerwacji sal',
    'USERNAME': 'system.rezerwacji.sal@gmail.com',
    'PASSWORD': 'systemrs16'
}